version: "3.9"

services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db # bind
    env_file:
      - ./env/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./:/code # bind
    tty: true # -t flag
    stdin_open: true # -i flag
    env_file:
      - ./env/.env

