version: "3.9"

services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db # bind
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    tty: true # -t flag
    stdin_open: true # -i flag
    # env_file:
    #   - .env


