version: "3.9"

services:
  db:
    image: mongo
    restart: always
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
  web:
    image: vixxadesso/ati
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ../media/:/media # bind
    tty: true # -t flag
    # env_file:
    #   - .env
