version: "3.9"

services:
  db:
    image: mongo
    restart: always
    volumes:
      - /data/db
    env_file:
      - ./env/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  web:
    image: vixxadesso/ati
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./src/media/:/code/media # bind
    tty: true # -t flag
    env_file:
      - ./env/.env

