// import "js/components/reply-button.ts";
// import "js/components/tougleFriend.ts";
// import "js/components/search.ts";
// import "js/components/chat.ts";
// import "js/components/changeTheme.ts";
import "js/components/create-publication.ts";
// import "js/components/mobile-navmenu.ts";
// import "js/components/changeTheme.ts";
// import "js/components/description-input.ts";
import "js/components/editCard.ts";
// import "js/components/changeImages.ts";
// import "js/components/sendMessages.ts";
// import "js/components/sendComments.ts";
// import "js/components/listChats.ts";