name: Continuos Integration

on:
  pull_request:
    branches: [ master, develop ]
    types: [ synchronize ]
  push:
    branches: [ master ]

jobs:
  setup_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python dependencies
        uses: ./.github/actions/pip

  setup_yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        uses: ./.github/actions/yarn

  test:
    needs: [ setup_yarn, setup_python ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get python dependencies from cache
        uses: ./.github/actions/pip
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
      - name: Get yarn dependencies from cache
        uses: ./.github/actions/yarn
      - name: Build static files
        run: |
          yarn install
          yarn build
      - name: Run pylint
        run: |
          ./scripts/linter.sh
      - name: Run pytest
        run: |
          ./scripts/test.sh

 # docker:
 #   needs: test
 #   if: github.ref == 'refs/heads/master'
 #   runs-on: ubuntu-latest
 #   steps:
 #     - uses: actions/checkout@v2
 #     - name: Build docker image
 #       run: |
 #         setup_prod
 #     - name: Set up QEMU
 #       uses: docker/setup-qemu-action@v1
 #     - name: Set up Docker Buildx
 #       uses: docker/setup-buildx-action@v1
 #     - name: Login to DockerHub
 #       uses: docker/login-action@v1
 #       with:
 #         username: ${{ secrets.DOCKERHUB_USERNAME }}
 #         password: ${{ secrets.DOCKERHUB_TOKEN }}
 #     - name: Build and push
 #       uses: docker/build-push-action@v2
 #       with:
 #         context: .
 #         push: true
 #         tags: vixxadesso/ati:latest

 # deploy:
 #   needs: docker
 #   runs-on: ubuntu-latest
 #   steps:
 #     - uses: actions/checkout@v2
 #     - name: Save branch name
 #       id: branch
 #       run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
 #     - name: Executing remote ssh commands using ssh key
 #       uses: appleboy/ssh-action@master
 #       with:
 #         host: ${{ secrets.HOST }}
 #         username: ${{ secrets.USERNAME }}
 #         key: ${{ secrets.KEY }}
 #         port: ${{ secrets.PORT }}
 #         script: |
 #           echo "Deploy... ${{ steps.branch.outputs.short_ref }}"
