name: auto-format
on:
  pull_request:
    types:
      [ synchronize ]
jobs:
  format:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: .
      - name: prettier
        run: yarn prettier --write static_src/**/*.js
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'autoformat'
          git config --global user.email 'autoformat@vittorioadesso.com'
          git remote set-url origin https://x-access-token:${{ secrets.BOT_FORMATTER_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "bot: Automated formatting changes"
          git push
